debug output fixed

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -52,23 +52,13 @@ jobs:
             cmake --build build/Debug;
           fi
         "
-        
-    - name: Debug Presets
-<<<<<<< HEAD
-      run: |
-        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace zombieanfuehrer/avr-gcc-conan-cmake:latest /bin/sh -c "
-          echo 'Content of CMakePresets.json:'
-          cat /workspace/build/Debug/generators/CMakePresets.json
-          echo 'Content of CMakeUserPresets.json:'
-          cat /workspace/CMakeUserPresets.json
-        "
-=======
-      if: failure()
-      run: |
-        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace zombieanfuehrer/avr-gcc-conan-cmake:latest /bin/sh -c "
-          echo 'Content of CMakePresets.json:'
-          cat /workspace/build/Debug/generators/CMakePresets.json || echo 'CMakePresets.json not found'
-          echo 'Content of CMakeUserPresets.json:'
-          cat /workspace/CMakeUserPresets.json || echo 'CMakeUserPresets.json not found'
-        "
->>>>>>> 302965a (debug output)
+
+        - name: Debug Presets
+        if: failure()
+        run: |
+          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace zombieanfuehrer/avr-gcc-conan-cmake:latest /bin/sh -c "
+            echo 'Content of CMakePresets.json:'
+            cat /workspace/build/Debug/generators/CMakePresets.json || echo 'CMakePresets.json not found'
+            echo 'Content of CMakeUserPresets.json:'
+            cat /workspace/CMakeUserPresets.json || echo 'CMakeUserPresets.json not found'
+          "
