debug output

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -54,6 +54,7 @@ jobs:
         "
         
     - name: Debug Presets
+<<<<<<< HEAD
       run: |
         docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace zombieanfuehrer/avr-gcc-conan-cmake:latest /bin/sh -c "
           echo 'Content of CMakePresets.json:'
@@ -61,3 +62,13 @@ jobs:
           echo 'Content of CMakeUserPresets.json:'
           cat /workspace/CMakeUserPresets.json
         "
+=======
+      if: failure()
+      run: |
+        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace zombieanfuehrer/avr-gcc-conan-cmake:latest /bin/sh -c "
+          echo 'Content of CMakePresets.json:'
+          cat /workspace/build/Debug/generators/CMakePresets.json || echo 'CMakePresets.json not found'
+          echo 'Content of CMakeUserPresets.json:'
+          cat /workspace/CMakeUserPresets.json || echo 'CMakeUserPresets.json not found'
+        "
+>>>>>>> 302965a (debug output)
