fix

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -52,19 +52,25 @@ jobs:
         "
     
     - name: Extract Package Folder Path
-      id: extract_path
       run: |
         PACKAGE_FOLDER=$(grep 'Package folder' conan_output.txt | awk '{print $3}')
+        if [ -z "$PACKAGE_FOLDER" ]; then
+          echo "Error: Package folder not found in conan_output.txt"
+          exit 1
+        fi
         echo "PACKAGE_FOLDER=$PACKAGE_FOLDER" >> $GITHUB_ENV
         echo "Package folder path: $PACKAGE_FOLDER"
-
+    
     - name: Extract Package Name
-      id: extract_package_name
       run: |
         PACKAGE_NAME=$(grep 'Full package reference' conan_output.txt | awk -F'[:#]' '{print $2}' | sed 's/\//_/g')
+        if [ -z "$PACKAGE_NAME" ]; then
+          echo "Error: Package name not found in conan_output.txt"
+          exit 1
+        fi
         echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
         echo "Package name: $PACKAGE_NAME"
-
+    
     - name: Compress Package Folder
       run: |
         tar -czvf package.tar.gz -C $PACKAGE_FOLDER .
