....

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -70,13 +70,22 @@ jobs:
     
     - name: Extract Package Name
       run: |
-        PACKAGE_NAME=$(grep -oP 'Full package reference \K.*' conan_output.txt)
-        if [ -z "$PACKAGE_NAME" ]; then
-          echo "Error: Package name not found in conan_output.txt"
+        FULL_REFERENCE=$(grep -oP 'Full package reference: \K.*' conan_output.txt)
+        if [ -z "$FULL_REFERENCE" ]; then
+          echo "Error: 'Full package reference:' not found in conan_output.txt"
           exit 1
         fi
-        echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
-        echo "Package name: $PACKAGE_NAME"
+        echo "Full package reference: $FULL_REFERENCE"
+        PACKAGE_NAME_VERSION=$(echo "$FULL_REFERENCE" | grep -oP '^[^#]+')
+        if [ -z "$PACKAGE_NAME_VERSION" ]; then
+          echo "Error: Package name and version not found in full package reference"
+          exit 1
+        fi
+        echo "Package name and version: $PACKAGE_NAME_VERSION"
+        PACKAGE_NAME_VERSION=$(echo "$PACKAGE_NAME_VERSION" | sed 's/\//_/g')
+
+        echo "PACKAGE_NAME_VERSION=$PACKAGE_NAME_VERSION" >> $GITHUB_ENV
+        echo "Package name: $PACKAGE_NAME_VERSION"
     
     - name: Compress Package Folder
       run: |
